// templates/react-starter/src/components/Navigation.jsx
function Navigation({ currentPage, totalPages, onNext, onPrevious }) {
  return (
    <nav className="navigation">
      <button 
        onClick={onPrevious}
        disabled={currentPage === 1}
      >
        ← Previous
      </button>
      <span className="page-indicator">
        Page {currentPage} of {totalPages}
      </span>
      <button 
        onClick={onNext}
        disabled={currentPage === totalPages}
      >
        Next →
      </button>
    </nav>
  );
}

export default Navigation;

// templates/vue-starter/src/components/Navigation.vue
<template>
  <nav class="navigation">
    <button 
      @click="$emit('previous')"
      :disabled="currentPage === 1"
    >
      ← Previous
    </button>
    <span class="page-indicator">
      Page {{ currentPage }} of {{ totalPages }}
    </span>
    <button 
      @click="$emit('next')"
      :disabled="currentPage === totalPages"
    >
      Next →
    </button>
  </nav>
</template>

<script>
export default {
  name: 'Navigation',
  props: {
    currentPage: {
      type: Number,
      required: true
    },
    totalPages: {
      type: Number,
      required: true
    }
  },
  emits: ['next', 'previous']
};
</script>
