// templates/react-starter/src/pages/Page1.jsx
function Page1() {
  return (
    <div className="page">
      <h2>Page 1: Introduction</h2>
      <p>Welcome to this React-based SCORM course!</p>
      <p>This template demonstrates how to build e-learning content with React and SCORM tracking.</p>
      <ul>
        <li>Navigate using the buttons below</li>
        <li>Your progress is automatically saved</li>
        <li>Close and reopen to test resume functionality</li>
        <li>Complete all pages to finish the course</li>
      </ul>
    </div>
  );
}

export default Page1;

// templates/vue-starter/src/pages/Page1.vue
<template>
  <div class="page">
    <h2>Page 1: Introduction</h2>
    <p>Welcome to this Vue-based SCORM course!</p>
    <p>This template demonstrates how to build e-learning content with Vue 3 and SCORM tracking.</p>
    <ul>
      <li>Navigate using the buttons below</li>
      <li>Your progress is automatically saved</li>
      <li>Close and reopen to test resume functionality</li>
      <li>Complete all pages to finish the course</li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'Page1'
};
</script>
