// templates/react-starter/src/pages/Page2.jsx
function Page2() {
  return (
    <div className="page">
      <h2>Page 2: Content</h2>
      <p>This is the second page of your course.</p>
      <p>With React, you can build rich interactive experiences:</p>
      <ul>
        <li>Dynamic components</li>
        <li>State management</li>
        <li>Interactive quizzes</li>
        <li>Real-time updates</li>
        <li>Animations and transitions</li>
      </ul>
      <div className="info-box">
        <strong>💡 Tip:</strong> The useScorm hook provides easy access to SCORM functionality throughout your components.
      </div>
    </div>
  );
}

export default Page2;

// templates/vue-starter/src/pages/Page2.vue
<template>
  <div class="page">
    <h2>Page 2: Content</h2>
    <p>This is the second page of your course.</p>
    <p>With Vue, you can build rich interactive experiences:</p>
    <ul>
      <li>Reactive data binding</li>
      <li>Composable logic</li>
      <li>Interactive quizzes</li>
      <li>Real-time updates</li>
      <li>Smooth transitions</li>
    </ul>
    <div class="info-box">
      <strong>💡 Tip:</strong> The useScorm composable provides easy access to SCORM functionality throughout your components.
    </div>
  </div>
</template>

<script>
export default {
  name: 'Page2'
};
</script>
